import os, sys
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
LINE_WIDTH = 2
ACTIVATE_LASER = False
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
menu_open = False
ASTEROID_MIN_RADIUS = 30
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 1.3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

PAUSED = False

def restart_program():
    os.execv(sys.executable, ['python'] + sys.argv)
